### ISSUE TITLE
what's the problem when run the program

### ISSUE THREAD

**Issue by zzusec** [Aidennnn33/cloudgazer#3]
Traceback (most recent call last):
  File "cloudgazer.py", line 91, in <module>
    main()
  File "cloudgazer.py", line 77, in main
    results = find_real_ip(ip_list, HEADERS)
  File "cloudgazer.py", line 52, in find_real_ip
    'real_ip': [d['ip_address'] for d in res['protected_ip']['data']],
KeyError: 'protected_ip'

**Comment by polyphia** [comment]
same issue
